networks:
  go_api:

services:

  go:
    container_name: go_container
    build:
      context: './app/'
    # image: go_api-go
    # pull_policy: never
    ports:
      - "8071:8071"
    volumes:
      - ./app:/app
      - ./app/logs:/app/logs
    networks:
      - go_api

  # postgre:
  # db:
  #   image: postgres:16
  #   container_name: go_db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: pwd
  #     POSTGRES_DB: tm
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #     - ./db_dump:/docker-entrypoint-initdb.d # Mount SQL script
  #   networks:
  #     - go_api

  # # redis:
  # redis:
  #   # image: arm64v8/redis
  #   image: redis
  #   ports:
  #     - "${REDIS_PORT:-6379}:6379"
  #   volumes:
  #     - ./redis:/var/lib/redis
  #     - ./redis/redis.conf:/etc/redis/redis.conf
  #   command: redis-server /etc/redis/redis.conf
  #   restart: always
  #   networks:
  #     - go_api
